### ISSUE TITLE
File fails to upload without exif:DateTimeOriginal:  e.g. 2014:09:13 13:07:04

### ISSUE THREAD

**Issue by quistian** [vladak/flickrknob#8]
My scanning software does not add the DateTimeOriginal EXIF field. Without it, flickrknob fails. Perhaps if it's not there as a default the date of file creation could be used. Otherwise I will need to add the EXIF data to each file before uploading. And as they are scanned images, one does not always know the DateTimeOriginal.

**Comment by vladak** [comment]
Wow, someone (besides myself) is using flickrknob :-)

Falling back to last modified date of the file is sensible thing to do.

**Comment by quistian** [comment]
Hehehe.. I am always looking for some useful Python/Flickr Upload tools. I have re-written some of your code to use the file datetime.datetime when the DateTimeOriginal EXIF is not present. Still not really understanding:
a. How the -D deduplicate flag works
b. Why one would want two of the duplicates uploaded, given they are in different Album sets.

**Comment by vladak** [comment]
The -D is still disabled (#6) as it depends on flickrapi Python library to accept my PR - I don't really want to fork it.

The problem I have with duplicates is with duplicate photo handling in the official Flickr uploader. It enables duplication detection by default. When a set of photos is uploaded to newly created album and the upload API decides that some of the photos are duplicates, the official uploader will not assign the duplicate photos to the new album.

**Comment by quistian** [comment]
Tks... And I assume the Flickr Uploader does duplication checking on the local end? Given a Flickr account with say 1M photos, I doubt the remote end has a  database say of signatures for each one, which can be checked ahead of time before uploading or not. I don't see that (yet) in the Flickr API documentation. (https://www.flickr.com/services/api/upload.api.html)

**Comment by vladak** [comment]
The dedup check is done on Flickr servers; there is probably some fingerprint generated from both data and metadata once the photo is uploaded. The fingerprint is likely stored in a database in whatever cloud Flickr uses at the moment. The API does not directly document the dedup check, (which I raised to Flickr support and they promised to fix it, someday) however if you carefully inspect the contents of the https://www.flickr.com/services/api/upload.api.html , you will find this:
> 9: Duplicate photo/video detected
>    The uploaded photo or video was identified as a duplicate within the user's account. Only applies if dedup_check = 1 or dedup_check = 2. Will also return duplicate_photo_id and duplicate_photo_status values

Adding this parameter actually works, hence my claim about server side checking above.

**Comment by vladak** [comment]
The only problem with -D in flickrknob is that the `flickrapi` Python package considers the error 9 (duplicate photo) as hard error and raises exception for that. In order to do something meaningful however (like adding the photo to an album), the exception would have to carry the photo ID of the duplicate photo (which is returned from the API call as the API documentation explains and my testing confirmed), hence my PR submitted for `flickrapi`.
